name: Deploy Frontend to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test_and_deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: frontend

    - name: Run Playwright tests
      run: npm test
      working-directory: frontend

    - name: Build Frontend
      run: npm run build
      working-directory: frontend

    - name: Deploy Frontend to Render
      if: success()
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}' \
          https://api.render.com/deploy/srv-cqpm3qtsvqrc73fu9qsg
